### ISSUE TITLE
同一个句子每次生成的embedding都有细微的不同

### ISSUE THREAD

**Issue by wjddd** [georgechen1827/ChatGLM-text-embedding#1]
模型是直接使用ChatGLM-6B-INT4，没有微调过，多次生成同一个句子的embedding，每次的结果都不同。

**Comment by georgechen1827** [comment]
我稍微看了一下，好像没有发现这样的问题
<img width="1242" alt="image" src="https://user-images.githubusercontent.com/57535797/233983522-406ae6ea-c860-4184-8d2b-4067ec6bb997.png">
如果每次都有细微的不同的话，也有可能是精度误差造成的

**Comment by wjddd** [comment]
> 我稍微看了一下，好像没有发现这样的问题 <img alt="image" width="1242" src="https://user-images.githubusercontent.com/57535797/233983522-406ae6ea-c860-4184-8d2b-4067ec6bb997.png"> 如果每次都有细微的不同的话，也有可能是精度误差造成的

估计真的是精度误差的问题，谢谢~
